// Copyright (c) 2026 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// This pipeline builds the Horizon GNOME base image for GCP Cloud Workstations.
// Bootable GNOME + gnome-remote-desktop + Guacamole (DinD), consuming
// horizon-preflight via BASE_IMAGE. Pipeline uses BuildKit.
//
// References:
//   * https://github.com/moby/buildkit
//   * Image: https://hub.docker.com/r/moby/buildkit
//   * Upstream: https://github.com/sce-taid/cloud-workstations-custom-image-examples/tree/main/examples/images/gnome

pipeline {
  // Parameters defined in workloads/cloud-workstations/pipelines/workstation-images/horizon-gnome/groovy/job.groovy

  agent none

  environment {
    REGISTRY="${env.CLOUD_REGION}-docker.pkg.dev"
    DESTINATION="${REGISTRY}/${env.CLOUD_PROJECT}/${env.CLOUD_WS_HORIZON_GNOME_IMAGE_NAME}"
    PUSH="${NO_PUSH == "true" ? "false" : "true"}"
    HORIZON_DOMAIN="${env.HORIZON_DOMAIN}"
    GOOGLE_CLOUD_PROJECT="${env.CLOUD_PROJECT}"
    // BASE_IMAGE comes from job parameter (default: published horizon-preflight:latest).

    // Same android build-node pool pattern as horizon-asfp / horizon-android-studio.
    // Default sdv-node-pool (n1-standard-4, ~12Gi allocatable) cannot schedule a GNOME
    // desktop image build; android nodes (c2d-highcpu-112) are autoscaled for this.
    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          cloud_ws_horizon_gnome_build_pod: "true"
      spec:
        tolerations:
          - key: workloadType
            operator: Equal
            value: android
            effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                - key: cloud_ws_horizon_asfp_build_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                - key: cloud_ws_horizon_android_studio_build_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                - key: cloud_ws_horizon_gnome_build_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-cloud-ws-image-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: buildkit
          image: moby/buildkit:${BUILDKIT_RELEASE_TAG}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 98000m
              memory: 180000Mi
            requests:
              cpu: 98000m
              memory: 180000Mi
        nodeSelector:
          workloadLabel: android
    """.stripIndent()
  }

  stages {
    stage ('Start instance'){
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Docker Credentials'){
          steps {
            script {
              currentBuild.description = "NO_PUSH=${env.NO_PUSH}" + "<br>" + "BASE_IMAGE=${env.BASE_IMAGE}" + "<br>" + "$BUILD_USER"
            }
            container(name: 'buildkit') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  wget -nv -O docker-credential-gcr.tgz ${DOCKER_CREDENTIALS_URL}
                  tar -zxf docker-credential-gcr.tgz
                  chmod +x docker-credential-gcr && mv docker-credential-gcr /usr/bin/
                  rm -f docker-credential-gcr*.tar.gz
                  docker-credential-gcr configure-docker --registries=${REGISTRY}
                '''
              }
            }
          }
        }

        stage ('Build Docker Image'){
          when { expression { env.IMAGE_TAG && env.BASE_IMAGE } }
          steps {
            container(name: 'buildkit') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  cd "${WORKSPACE}/workloads/cloud-workstations/pipelines/workstation-images/horizon-gnome/";
                  cp -r "${WORKSPACE}/workloads/cloud-workstations/pipelines/workstation-images/common-utils/" ./common-utils/;
                  buildctl build \
                   --frontend=dockerfile.v0 \
                   --local=dockerfile=. \
                   --local context=. \
                   --opt platform=linux/amd64 \
                   --opt build-arg:BASE_IMAGE=${BASE_IMAGE} \
                   --opt build-arg:HORIZON_DOMAIN=${HORIZON_DOMAIN} \
                   --opt build-arg:GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT} \
                   --opt build-arg:GCP_REGION=${CLOUD_REGION} \
                   --opt build-arg:CWS_BASE_IMAGE_TAG=${CWS_BASE_IMAGE_TAG} \
                   --opt build-arg:INSTALL_ANTIGRAVITY_AGENT=${INSTALL_ANTIGRAVITY_AGENT} \
                   --opt build-arg:ANTIGRAVITY_2_VERSION=${ANTIGRAVITY_2_VERSION} \
                   --opt build-arg:ANTIGRAVITY_2_TARBALL_URL=${ANTIGRAVITY_2_TARBALL_URL} \
                   --opt build-arg:ANTIGRAVITY_2_TARBALL_SHA256=${ANTIGRAVITY_2_TARBALL_SHA256} \
                   --registry-auth-tlscontext host=${REGISTRY},insecure=true \
                   --output=type=image,name=${DESTINATION}:${IMAGE_TAG},push=${PUSH}
                '''
              }
            }
          }
        }
      }
    }
  }
}
