# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

apiVersion: v2
name: storage-gcs-module-argo-workflows
description: storage-gcs-upload and storage-gcs-module-internal WorkflowTemplates (deployed after Argo Workflows CRDs are available)
version: 0.1.0
type: application
