# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

{{- if include "storage-gcs-module.mainEnv" . | eq "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-gcs-module
  namespace: {{ .Values.config.namespacePrefix }}horizon
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    iam.gke.io/gcp-service-account: gke-storage-gcs-module-sa@{{ .Values.config.projectID }}.iam.gserviceaccount.com
{{- end }}
